### ISSUE TITLE
Local runner crash

### ISSUE THREAD

**Issue by sorrge** [All-Cups/aicup22#29]
The Linux version. Unsure about circumstances. This happened may times. The output with the stack trace:
```[INFO  codegame::player::tcp] Waiting for connection on port 12475
[INFO  codegame::player::tcp] Waiting for connection on port 12476
[INFO  codegame::player::tcp] Waiting for connection on port 12477
[INFO  codegame::player::tcp] Waiting for connection on port 12478
[INFO  codegame::player::tcp] Waiting for connection on port 12479
[INFO  codegame::player::tcp] Waiting for connection on port 12480
[INFO  codegame::player::tcp] Got connection on port 12475
[INFO  codegame::player::tcp] Got connection on port 12476
[INFO  codegame::player::tcp] Got connection on port 12477
[INFO  codegame::player::tcp] Got connection on port 12478
[INFO  codegame::player::tcp] Got connection on port 12479
[INFO  codegame::player::tcp] Got connection on port 12480
[INFO  codegame::processor] Seed = 15244983733147585074
[INFO  codegame::processor] Game initialized in 230.63ms
[INFO  codegame::processor] Game started
[ERROR batbox::logger] panicked at 'called `Option::unwrap()` on a `None` value', src/logic/movement.rs:64:26
[ERROR batbox::logger]    0: batbox::logger::init_with::{{closure}}
       1: std::panicking::rust_panic_with_hook
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:702:17
       2: std::panicking::begin_panic_handler::{{closure}}
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:586:13
       3: std::sys_common::backtrace::__rust_end_short_backtrace
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:138:18
       4: rust_begin_unwind
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
       5: core::panicking::panic_fmt
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
       6: core::panicking::panic
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:48:5
       7: aicup22::logic::Logic::process_turn_impl
       8: aicup22::logic::Logic::process_turn
       9: <codegame::processor::processor_strategy::standard::Standard<G> as codegame::processor::processor_strategy::GameProcessorStrategy<G>>::process_turn
      10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
      11: std::thread::local::LocalKey<T>::with
      12: codegame::runner::run_with
      13: aicup22::main
      14: std::sys_common::backtrace::__rust_begin_short_backtrace
      15: std::rt::lang_start::{{closure}}
      16: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:280:13
          std::panicking::try::do_call
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
          std::panicking::try
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
          std::panic::catch_unwind
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
          std::rt::lang_start_internal::{{closure}}
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:128:48
          std::panicking::try::do_call
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
          std::panicking::try
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
          std::panic::catch_unwind
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
          std::rt::lang_start_internal
                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:128:20
      17: main
      18: __libc_start_main
                 at ./csu/../csu/libc-start.c:308:16
      19: _start
    
[INFO  codegame::player::tcp] Dropping tcp player on port 12475
[INFO  codegame::player::stream] Waiting for run command to exit
[INFO  codegame::player::tcp] Dropping tcp player on port 12476
[INFO  codegame::player::stream] Waiting for run command to exit
[INFO  codegame::player::tcp] Dropping tcp player on port 12477
[INFO  codegame::player::stream] Waiting for run command to exit
[INFO  codegame::player::tcp] Dropping tcp player on port 12478
[INFO  codegame::player::stream] Waiting for run command to exit
[INFO  codegame::player::tcp] Dropping tcp player on port 12479
[INFO  codegame::player::stream] Waiting for run command to exit
[INFO  codegame::player::tcp] Dropping tcp player on port 12480
[INFO  codegame::player::stream] Waiting for run command to exit
```

**Comment by kuviman** [comment]
Check the update
https://github.com/All-Cups/aicup22/releases/tag/v1.2.0
This should be fixed, please reopen if not
