### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path '/.dotnet' is denied.

### ISSUE THREAD

**Issue by oakio** [All-Cups/aicup22#39]
Ошибка при запуске стратегии на C# NET6.0. 
По stack trace видно, что ошибка возникает не в коде пользователя.

```
System.UnauthorizedAccessException: Access to the path '/.dotnet' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateDirectory(String path)
   at Microsoft.DotNet.Configurer.FileSystemExtensions.<>c__DisplayClass0_0.<CreateIfNotExists>b__0()
   at Microsoft.DotNet.Cli.Utils.FileAccessRetrier.RetryOnIOException(Action action)
   at Microsoft.DotNet.Configurer.FileSystemExtensions.CreateIfNotExists(IFileSystem fileSystem, String filePath)
   at Microsoft.DotNet.Configurer.FileSentinel.Create()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by kuviman** [comment]
Насколько я понимаю, ошибка локальная? В таком случае проверьте что dotnet корректно установлен

**Comment by oakio** [comment]
Нет, ошибка на сервере. Локально все работает.
Например битва 397577 (https://cups.online/api_v2/battles/results/963052/get_stdout_file/).

**Comment by oakio** [comment]
Выяснил, что ошибка возникает если csproj файл называется иначе (не как AiCup22.csproj)

**Comment by DenomikoN** [comment]
Тоже столкнулся, ответ не очевиден.
